### ISSUE TITLE
bug(vax,azerbaijan): current script crashes due to regex issue

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2534]
### Description

The current script crashes due to a regex issue. The data was last updated on Feb 17.

```
2022-03-07 10:20:38,206 ERROR    VAX - cowidev.vax.incremental.azerbaijan: ❌ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py", line 39, in run
    module.main()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py", line 109, in main
    Azerbaijan().export()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py", line 95, in export
    data = self.read().pipe(self.pipeline)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py", line 26, in read
    data = self._parse_data(soup)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py", line 41, in _parse_data
    total_vaccinations, people_vaccinated, people_fully_vaccinated, total_boosters = self._parse_metrics(text)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py", line 74, in _parse_metrics
    total_vaccinations = re.search(self.regex["total"], text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Rouein** [comment]
this is due to a change of format in the document , they have added "Pozitiv nəticədən sonra
"Buster" doza vaksinlərin sayı" , which roughly translates to "booster doses after testing positive". I am not sure how to categorize it , would it fit into fully vaccinated ?

**Comment by lucasrodes** [comment]
Fixed in https://github.com/owid/covid-19-data/pull/2541
