### ISSUE TITLE
bug(vax,colombia): script crashes due to unassigned variable

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2535]
### Description

The data was last updated on Feb 23.

```
2022-03-07 10:22:48,093 ERROR    VAX - cowidev.vax.incremental.colombia: ❌ local variable 'total_vaccinations' referenced before assignment
Traceback (most recent call last):
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py", line 39, in run
    module.main()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/colombia.py", line 95, in main
    Colombia().export()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/colombia.py", line 77, in export
    data = self.read()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/colombia.py", line 21, in read
    df = self._parse_data(ws)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/colombia.py", line 47, in _parse_data
    first_doses = total_vaccinations - second_doses - unique_doses - boosters
UnboundLocalError: local variable 'total_vaccinations' referenced before assignment
```

**Comment by lucasrodes** [comment]
Source changed format. I reached out to the source but got no answer. Therefore, I have switched to PAHO instead.
