### ISSUE TITLE
bug(vax,hungary): current script crashes due to regex issue

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2536]
### Description

The current script crashes due to a regex issue. The data was last updated on Mar 3.

```
2022-03-07 10:24:26,894 ERROR    VAX - cowidev.vax.incremental.hungary: ❌ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py", line 39, in run
    module.main()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/hungary.py", line 141, in main
    Hungary().export()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/hungary.py", line 133, in export
    df = self.read(last_update)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/hungary.py", line 29, in read
    data_, proceed = self.parse_data(soup, last_update)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/hungary.py", line 44, in parse_data
    **self.parse_data_news_page(soup),
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/hungary.py", line 75, in parse_data_news_page
    people_vaccinated = clean_count(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by lucasrodes** [comment]
Regex changed because second booster data has been added to the daily report. I updated regex accordingly
