### ISSUE TITLE
bug: Kazakhstan script crashes due to missing booster data

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2543]
### Description

```
2022-03-08 10:48:16,457 ERROR    VAX - cowidev.vax.incremental.kazakhstan: ❌ list index out of range
Traceback (most recent call last):
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py", line 39, in run
    module.main()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py", line 65, in main
    data = read(source).pipe(pipeline)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py", line 15, in read
    total_boosters = parse_boosters(driver)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py", line 35, in parse_boosters
    elem = [e for e in elems if "Всего" in e.find_element_by_xpath("..").text][0]
IndexError: list index out of range
```

**Comment by lucasrodes** [comment]
When no booster data is available, leave `total_boosters` and `total_vaccinations` empty but still collect `people_vaccinated` and `people_fully_vaccinated`.
