### ISSUE TITLE
bug: Kenya script crashes due to regex

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2544]
### Description

```
2022-03-08 10:53:05,304 ERROR    VAX - cowidev.vax.incremental.kenya: ❌ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py", line 39, in run
    module.main()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kenya.py", line 118, in main
    Kenya().export()
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kenya.py", line 113, in export
    df = self.read().pipe(self.pipeline)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kenya.py", line 39, in read
    total_vaccinations, people_vaccinated, people_fully_vaccinated, total_boosters = self._parse_metrics(text)
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kenya.py", line 78, in _parse_metrics
    metrics = {
  File "/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/kenya.py", line 79, in <dictcomp>
    metric: clean_count(re.search(regex, pdf_text).group(1)) for metric, regex in self.regex["metrics"].items()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Rouein** [comment]
There is an easy solution to adjust the regex but the same issue might occur later. Tabula might be a better option.

**Comment by Rouein** [comment]
It's better if tabula is used. The documents also contain age data and the vaccine names are wrong(historical data needs to be corrected)

**Comment by lucasrodes** [comment]
I'm on it!

**Comment by Rouein** [comment]
> I'm on it!

-The document lacks the age group population.
-If you are going to use tabula , it would be easier to parse the date from the link of the PDF file.

**Comment by lucasrodes** [comment]
> - The document lacks the age group population.
Will not collect vaccination data by age group for now.

> - If you are going to use tabula , it would be easier to parse the date from the link of the PDF file.
Makes sense!

**Comment by lucasrodes** [comment]
Backfilled the data for Kenya and corrected vaccines.

The script is now using `tabula` and extracting the date from the URL.
