### ISSUE TITLE
data: cases_deaths pipeline with data from WHO

### ISSUE THREAD

**Issue by molily** [owid/covid-19-data#2824]
### Country

all

### Domain

Cases

### Which data is inaccurate or missing?

Hello, happy new year!

It seems to me that the cases_deaths pipeline has not imported/uploaded new data since 11 days (https://ourworldindata.org/covid-cases).

The WHO has relaunched their COVID-19 dashboard on December 22th. The URLs have changed from https://covid19.who.int/ to  https://data.who.int/dashboards/covid19/.

The cases_deaths pipeline ([extract.py](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/cases_deaths/extract.py)) apparently pulls data from https://covid19.who.int/WHO-COVID-19-global-data.csv. This URL still works but is now a double temporary redirect to https://data.who.int/dashboards/covid19//WHO-COVID-19-global-data.csv and then to some [CDN URL](https://srhdpeuwpubsa.blob.core.windows.net/whdh/COVID/WHO-COVID-19-global-data.csv). As far as I can see, the format should still be the same.

This WHO-COVID-19-global-data.csv has weekly data for 2023-12-24 but it's not on OWID yet, that's why I'm asking.

This is what I get when I run the pipeline locally:

```
% cowid casedeath generate
/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
2024-01-02 16:19:46,167 INFO     Cases/Deaths: Loading data…
Traceback (most recent call last):
  File "/Users/molily/projects/covid-19-data/scripts/src/cowidev/cases_deaths/extract.py", line 15, in load_data
    df = pd.read_csv(URL)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/molily/projects/covid-19-data/scripts/venv/bin/cowid", line 8, in <module>
    sys.exit(cli())
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/molily/projects/covid-19-data/scripts/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/molily/projects/covid-19-data/scripts/src/cowidev/cmd/cases_deaths.py", line 17, in click_cd_generate
    feedback_log(
  File "/Users/molily/projects/covid-19-data/scripts/src/cowidev/cmd/commons/utils.py", line 34, in feedback_log
    raise err
  File "/Users/molily/projects/covid-19-data/scripts/src/cowidev/cmd/commons/utils.py", line 25, in feedback_log
    func(**function_kwargs)
  File "/Users/molily/projects/covid-19-data/scripts/src/cowidev/cases_deaths/generate.py", line 13, in generate_dataset
    df = load_data(server_mode)
  File "/Users/molily/projects/covid-19-data/scripts/src/cowidev/cases_deaths/extract.py", line 23, in load_data
    raise ValueError("Could not load data from WHO.")
ValueError: Could not load data from WHO.
```

I have no clue of Python, but apparently the server (the CDN?) is returning 403 Forbidden for the script?

### Why do you think the data is inaccurate or missing?

WHO-COVID-19-global-data.csv has weekly data for 2023-12-24 but it's not on OWID yet

**Comment by lucasrodes** [comment]
Thanks for reporting and the careful analysis, @molily!

I have fixed a couple of things in our pipeline so that we can download and report the up-to-date WHO data.

On the one hand, I have updated the reference links to the new one (https://data.who.int/dashboards/covid19). On the other hand, I have changed the usage of `pandas.read_csv` to our custom function [`read_csv_from_url`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/utils/web/download.py#L55-L63) which seems to work (does not return 403 error).

The data should be live soon in [our explorers](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&country=IND~USA~GBR~CAN~DEU~FRA&pickerSort=desc&pickerMetric=new_cases_smoothed_per_million&Metric=Confirmed+cases&Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false) (it takes some more time to be reflected in these). For the time being, the data is updated in our [stand-alone charts](https://ourworldindata.org/covid-cases#weekly-and-biweekly-cases-where-are-confirmed-cases-increasing-or-falling).
